### ISSUE TITLE
calculation mistake in E11.7

### ISSUE THREAD

**Issue by IanLee1024** [estamos/Neural-Network-Design-Solutions-Manual#7]
when calculating the output of second layer, the b^2(0) actually is 3,  but calculate as 2

**Comment by estamos** [comment]
Hi @IanLee1024,

I just updated E11_7 fixing this issue in calculations, based on the previous solution of @OUStudent.
If you are working, studying on this textbook you are encouraged to open further issues / pull requests to contribute.

Regards,
Evangelos.

**Comment by IanLee1024** [comment]
thank you! this repo is helpful for me.
